---
HOSTS:
  ubuntu-16.04-x64:
    docker_cmd: '["/sbin/init"]'
    docker_image_commands:
      - 'apt-get update'
      - 'apt-get install --yes locales'
      - 'locale-gen en_US.UTF-8'
    docker_preserve_image: true
    hypervisor: 'docker'
    image: 'ubuntu:16.04'
    platform: 'ubuntu-16.04-amd64'
CONFIG:
  trace_limit: 200
