---
fixtures:
  forge_modules:
    apt: 'puppetlabs/apt'
    archive: 'puppet/archive'
    git: 'puppetlabs/git'
    inifile: 'puppetlabs/inifile'
    nodejs: 'puppet/nodejs'
    php: 'puppet/php'
    stdlib: 'puppetlabs/stdlib'
    systemd: 'camptocamp/systemd'
    vcsrepo: 'puppetlabs/vcsrepo'
  symlinks:
    phabricator: '#{source_dir}'
